version: '3.8'

services:
  # Servicio REST
  rest-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/person_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/person_app
    networks:
      - app-network

  # Servicio MongoDB
  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network

  # Servicio MariaDB
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: persona_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d  # Asegúrate de que los scripts estén aquí
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo_data:
  mariadb_data:
